services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_DBNAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    ports:
      - "${DB_PORT}:5432"
    networks:
      - prosel-elton-network
  redis-cache:
    image: "redis:8.0-rc1-alpine"
    container_name: redis-cache
    restart: always
    env_file: .env
    ports:
      - "${REDIS_CACHE_PORT}:6379"
    command: redis-server --requirepass ${REDIS_CACHE_PASSWORD} --protected-mode no
    networks:
      - prosel-elton-network

networks:
  prosel-elton-network:
    driver: bridge
