services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_DBNAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    ports:
      - "${DB_PORT}:5432"
    networks:
      - prosel-elton-network
  redis-cache:
    image: "redis:8.0-rc1-alpine"
    container_name: redis-cache
    restart: always
    env_file: .env
    ports:
      - "${REDIS_CACHE_PORT}:6379"
    command: redis-server --requirepass ${REDIS_CACHE_PASSWORD} --protected-mode no
    networks:
      - prosel-elton-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686"  # Jaeger UI
      - "14268"
      - "14250"
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # http gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
    links:
      - jaeger
networks:
  prosel-elton-network:
    driver: bridge
